### ISSUE TITLE
What's the purpose of this repo?

### ISSUE THREAD

**Issue by Jeffwan** [vllm-project/vllm-nccl#1]
Hi Maintainer, 

Could i know the purpose of this repo? Do you like to build nccl optimization for vLLM?

**Comment by frostyplanet** [comment]
Instead of requiring user to download ~/.config/vllm/nccl/cu12/libnccl.so.2.18.1
Why this package could not detect via system installed libnccl2 and libnccl-dev ?

**Comment by youkaichao** [comment]
because of https://github.com/NVIDIA/nccl/issues/1234 and https://github.com/pypi/support/issues/3792 .
